items:
  - titre: Open Bioénergie
    repo: https://github.com/bioenergie/open
    topmenu:
      - name: Accueil
        url: /
        id: home
      - name: Comptabilité
        url: /comptabilite/
        id: comptabilite
      - name: Procédures
        url: /procedure/
        id: procedure
      - name: Reddition
        url: /reddition/
        id: reddition
      - name: Rétroaction
        url: /retroaction/
        id: retroaction
